version: '3.9'

services:
  kafka:
    image: confluentinc/cp-kafka:7.1.1
    environment:
      TZ: America/Guayaquil
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,EXTERNAL://localhost:9093
      KAFKA_BROKER_ID: '1'
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:9092,EXTERNAL://0.0.0.0:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    ports:
      - 9093:9093
    restart: on-failure
    volumes:
      - kafka_data:/var/lib/kafka/data
    depends_on:
      zookeeper:
        condition:
          service_healthy
    healthcheck:
      test: kafka-topics --bootstrap-server localhost:9092 --list > /dev/null 2>&1
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 30s

  zookeeper:
    image: confluentinc/cp-zookeeper:7.1.1
    environment:
      TZ: America/Guayaquil
      ZOOKEEPER_CLIENT_PORT: '2181'
      ZOOKEEPER_SERVERS: zookeeper:2888:3888
      ZOOKEEPER_SERVER_ID: '1'
      ZOOKEEPER_SYNC_LIMIT: '2'
      ZOOKEEPER_TICK_TIME: '2000'
    ports:
      - 2181:2181
    restart: on-failure
    volumes:
      - zookeeper_data:/var/lib/zookeeper/data
      - zookeeper_datalog:/var/lib/zookeeper/log
    healthcheck:
      test: nc -z localhost 2181
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 30s
  
  akhq:
    image: tchiotludo/akhq:latest
    ports:
      - 8080:8080
    restart: on-failure
    environment:
      TZ: America/Guayaquil
      AKHQ_CONFIGURATION: |
        akhq:
          connections:
            kafka-cluster:
              properties:
                bootstrap.servers: kafka:9092
    depends_on:
      kafka:
        condition:
          service_healthy
    healthcheck:
      test: curl -sf http://localhost:28081/health > /dev/null 2>&1
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 10s

volumes:
  kafka_data:
  zookeeper_data:
  zookeeper_datalog:

networks:
  default:
    external: true
    name: kafka-opentelemetry-sandbox_network
