ARG VERSION
FROM confluentinc/cp-schema-registry:${VERSION}
RUN curl -sLo /home/appuser/opentelemetry-javaagent.jar https://github.com/open-telemetry/opentelemetry-java-instrumentation/releases/latest/download/opentelemetry-javaagent.jar